version: '3.9'

services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "secure_root_password"
      MYSQL_DATABASE: Dinnin-db
      MYSQL_USER: Ryan
      MYSQL_PASSWORD: Password1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    hostname: "rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: Ryan
      RABBITMQ_DEFAULT_PASS: "@Password1"

  webapi:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7282:80"
    depends_on:
      - mysql
      - rabbitmq
volumes:
  mysql_data:
