version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "@Password1"
      MYSQL_DATABASE: Dinnin-db
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    hostname: "rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: Ryan
      RABBITMQ_DEFAULT_PASS: "@Password1"

volumes:
  mysql_data:
